apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    name: debug
    project: roboshop
spec:
  containers:
    - name: debug
      image: gsurapuraju/debug:v1
      imagePullPolicy: Always